// CMC Strategy Skill — shared types for Track 2 (BNBHack)
// A StrategySpec is the backtestable artifact generated by a skill invocation.

export type SkillType =
  | "momentum"            // RSI + MACD + Fear & Greed blended entry/exit
  | "sentiment_divergence" // flags when F&G vs technical momentum disagree
  | "regime_detection"    // switches strategy based on perps positioning
  | "perps_divergence";   // spot vs perps divergence (funding + L/S vs technicals)

export type AllowedRegime = "trending" | "ranging" | "unknown";

export interface SignalCondition {
  signal: string;                                    // e.g. "blended_signal", "rsi_signal", "funding_rate"
  operator: ">" | "<" | ">=" | "<=" | "between";
  threshold: number;
  threshold2?: number;                               // for "between"
  description: string;
}

export interface ExitRule {
  type: "stop_loss" | "take_profit" | "signal_reversal" | "time_limit";
  value: number;    // SL/TP: % from entry (e.g. 0.05 = 5%); time: bars; reversal: signal threshold
  description: string;
}

export interface PositionSizingRule {
  method: "fixed_risk" | "kelly" | "vol_scaled";
  riskPerTradePct: number;   // fraction of capital at risk per trade (e.g. 0.01 = 1%)
  maxPositionPct: number;    // max single position as fraction of portfolio
}

export interface RegimeFilter {
  allowedRegimes: AllowedRegime[];
  adxMin?: number;
  adxMax?: number;
}

export interface RiskLimits {
  maxDrawdownPct: number;
  maxOpenPositions: number;
  dailyLossLimitPct: number;
}

export interface MarketContext {
  fearGreedValue: number;
  fearGreedLabel: string;
  btcDominancePct: number;
  totalMarketCapUsd: number;
  regime: AllowedRegime;
  topMoverSymbol: string;
  topMoverChange24h: number;
}

// The primary Track 2 deliverable — a backtestable strategy spec
export interface StrategySpec {
  id: string;
  name: string;
  description: string;
  skillType: SkillType;
  universe: string[];                // e.g. ["BTC/USD", "ETH/USD", "SOL/USD"]

  // All entry conditions must be true simultaneously
  entryConditions: SignalCondition[];

  // Any exit condition triggers the trade close
  exitRules: ExitRule[];

  positionSizing: PositionSizingRule;
  regimeFilter?: RegimeFilter;
  riskLimits: RiskLimits;

  // Snapshot of the market state when the spec was generated (LLM context)
  generatedAt: string;
  marketContext: MarketContext;

  // LLM rationale for the spec choices
  rationale: string;
}

// Individual simulated trade record from backtest
export interface BacktestTrade {
  symbol: string;
  entryTime: number;    // unix seconds
  exitTime: number;
  entryPrice: number;
  exitPrice: number;
  direction: "long";    // paper mode: long-only
  returnPct: number;
  sizeUsd: number;
  exitReason: string;
}

// Full backtest result for a strategy spec against one or more symbols
export interface BacktestResult {
  specId: string;
  specName: string;
  symbols: string[];
  interval: "1h" | "4h" | "1d";
  period: { fromMs: number; toMs: number; bars: number };
  initialCapital: number;
  finalCapital: number;
  totalReturnPct: number;
  annualizedReturnPct: number;
  sharpeRatio: number;
  sortinoRatio: number;
  calmarRatio: number;
  maxDrawdownPct: number;
  winRate: number;
  totalTrades: number;
  avgTradeReturnPct: number;
  profitFactor: number;
  equityCurve: { time: number; value: number }[];
  trades: BacktestTrade[];
  ranAt: string;
}
